"""MCP-style gateway tools for ClawCam brain integrations."""

from clawcam_gateway.tools.clawcam_tools import (
    ToolContext,
    apply_config_patch,
    capture_now,
    create_alert_rule,
    create_schedule,
    export_detections_csv,
    generate_daily_summary,
    get_cloud_sync_status,
    get_device_state,
    get_inference_results,
    get_node_health,
    get_recent_detections,
    list_alert_rules,
    list_capabilities,
    list_firmware_builds,
    list_pending_commands,
    list_profiles,
    list_recent_alerts,
    list_schedule_runs,
    list_schedules,
    list_species_detections,
    list_state_transitions,
    queue_firmware_update,
    set_deployment_state,
    set_device_state,
)

__all__ = [
    "ToolContext",
    "apply_config_patch",
    "capture_now",
    "create_alert_rule",
    "create_schedule",
    "export_detections_csv",
    "generate_daily_summary",
    "get_cloud_sync_status",
    "get_device_state",
    "get_inference_results",
    "get_node_health",
    "get_recent_detections",
    "list_alert_rules",
    "list_capabilities",
    "list_firmware_builds",
    "list_pending_commands",
    "list_profiles",
    "list_recent_alerts",
    "list_schedule_runs",
    "list_schedules",
    "list_species_detections",
    "list_state_transitions",
    "queue_firmware_update",
    "set_deployment_state",
    "set_device_state",
]
